apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: kube-prometheus-stack-grafana
    app.kubernetes.io/instance: awesome-service
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 17.1.3
    chart: kube-prometheus-stack-17.1.3
    heritage: Helm
    release: awesome-service
  name: prometheus-awesomeservice
  namespace: {{ .Values.prometheusNamespace }}
spec:  
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - interval: 30s
    port: metrics
  selector:
    matchLabels:
      {{- include "awesome-service.labels" . | nindent 6 }}