apiVersion: v2
name: awesome-service
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
- name: kube-prometheus-stack
  version: 17.1.3
  repository: https://prometheus-community.github.io/helm-charts
